//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SchuelerModel", Namespace="http://schemas.datacontract.org/2004/07/SchulAppSOAP.Models")]
    public partial class SchuelerModel : object
    {
        private string AuditUserNameField = string.Empty;
        private string AuditUserRoleField = string.Empty;
        private int KlasseIdField;
        private string NameField = string.Empty;
        private int SchuelerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuditUserName
        {
            get
            {
                return this.AuditUserNameField;
            }
            set
            {
                this.AuditUserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuditUserRole
        {
            get
            {
                return this.AuditUserRoleField;
            }
            set
            {
                this.AuditUserRoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KlasseId
        {
            get
            {
                return this.KlasseIdField;
            }
            set
            {
                this.KlasseIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SchuelerId
        {
            get
            {
                return this.SchuelerIdField;
            }
            set
            {
                this.SchuelerIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISchuelerService")]
    public interface ISchuelerService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchuelerService/GetSchueler", ReplyAction="http://tempuri.org/ISchuelerService/GetSchuelerResponse")]
        System.Threading.Tasks.Task<ServiceReference1.SchuelerModel[]> GetSchuelerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchuelerService/GetSchuelerById", ReplyAction="http://tempuri.org/ISchuelerService/GetSchuelerByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference1.SchuelerModel> GetSchuelerByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchuelerService/AddSchueler", ReplyAction="http://tempuri.org/ISchuelerService/AddSchuelerResponse")]
        System.Threading.Tasks.Task<bool> AddSchuelerAsync(ServiceReference1.SchuelerModel schueler);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchuelerService/UpdateSchueler", ReplyAction="http://tempuri.org/ISchuelerService/UpdateSchuelerResponse")]
        System.Threading.Tasks.Task<bool> UpdateSchuelerAsync(ServiceReference1.SchuelerModel schueler);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchuelerService/DeleteSchueler", ReplyAction="http://tempuri.org/ISchuelerService/DeleteSchuelerResponse")]
        System.Threading.Tasks.Task<bool> DeleteSchuelerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchuelerService/DeleteSchuelerMitAudit", ReplyAction="http://tempuri.org/ISchuelerService/DeleteSchuelerMitAuditResponse")]
        System.Threading.Tasks.Task<bool> DeleteSchuelerMitAuditAsync(int id, string auditUserName, string auditUserRole);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ISchuelerServiceChannel : ServiceReference1.ISchuelerService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SchuelerServiceClient : System.ServiceModel.ClientBase<ServiceReference1.ISchuelerService>, ServiceReference1.ISchuelerService
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SchuelerServiceClient() : 
                base(SchuelerServiceClient.GetDefaultBinding(), SchuelerServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISchuelerService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SchuelerServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SchuelerServiceClient.GetBindingForEndpoint(endpointConfiguration), SchuelerServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SchuelerServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SchuelerServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SchuelerServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SchuelerServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SchuelerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SchuelerModel[]> GetSchuelerAsync()
        {
            return base.Channel.GetSchuelerAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SchuelerModel> GetSchuelerByIdAsync(int id)
        {
            return base.Channel.GetSchuelerByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> AddSchuelerAsync(ServiceReference1.SchuelerModel schueler)
        {
            return base.Channel.AddSchuelerAsync(schueler);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateSchuelerAsync(ServiceReference1.SchuelerModel schueler)
        {
            return base.Channel.UpdateSchuelerAsync(schueler);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSchuelerAsync(int id)
        {
            return base.Channel.DeleteSchuelerAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSchuelerMitAuditAsync(int id, string auditUserName, string auditUserRole)
        {
            return base.Channel.DeleteSchuelerMitAuditAsync(id, auditUserName, auditUserRole);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISchuelerService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISchuelerService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5210/SchuelerService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SchuelerServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISchuelerService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SchuelerServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISchuelerService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISchuelerService,
        }
    }
}
